#!/bin/bash

ETH_ADDRESS="0x4e1350db1c426ddec75f78b18cd7e96cce4dc2c4"
MINER_PATH="/usr/local/claymore95/"
MINER_NAME="mining_rig_main"
MINER_PARAMS="-U -v 9 -F http://eth1.nanopool.org:8888/$ETH_ADDRESS/$MINER_NAME"

tmux new-session -d
tmux rename-session 'mining-session'

tmux split-window 
tmux split-window -h
tmux split-window -t 0 -h

tmux send-keys -t 0 "cd $MINER_PATH" enter
tmux send-keys -t 0 "./mine.sh" C-m
tmux send-keys -t 2 'htop' enter
tmux send-keys -t 3 "watch ./nanopool-mon.py $ETH_ADDRESS" enter

tmux resize-pane -t 3 -R 17
tmux resize-pane -t 2 -R 11

tmux attach
